package com.njplastic.njplastic_api.production.mqtt;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * MQTT pulse published by the Arduino on the shared topic. The payload carries
 * the short machine code (resolved to a machine_id) and the wall-clock
 * time
 * "HH:MM:SS" generated by the microcontroller; the backend reconstructs the
 * full
 * TIMESTAMPTZ by combining it with the local date.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PulsePayload {

  @Schema(description = "Short code provisioned on the Arduino", example = "MAQ-01", nullable = false)
  @JsonProperty("machine_code")
  private String machineCode;

  @Schema(description = "Wall-clock time HH:MM:SS generated by the microcontroller (UTC-3)", example = "14:23:55", nullable = false)
  @JsonProperty("generated_at")
  private String generatedAt;

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("PulsePayload{machineCode=").append(machineCode)
        .append(", generatedAt=").append(generatedAt)
        .append('}');
    return sb.toString();
  }
}